#!/usr/bin/env python2.7

from Controller import *

imFolder = '/Users/tiagosn/Documents/datasets/UCSD_Anomaly_Dataset.v1p2/UCSDped2/Test/Test008/'
gtFolder = '/Users/tiagosn/Documents/datasets/UCSD_Anomaly_Dataset.v1p2/UCSDped2/Test/Test008_gt2/'

c = Controller(imFolder, gtFolder)
c.run()
